apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-test-server
  namespace: go-test-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-test-server
  template:
    metadata:
      labels:
        app: go-test-server
    spec:
      volumes:
        - name: go-test-config
          configMap:
            name: go-test-config
        - name: go-test-secret
          secret:
            secretName: go-test-secret
      containers:
      - name: go-test-server
        image: ghcr.io/grimoh/go-test-server/go-test-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
          requests:
            memory: "256Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
              - name: Host
                value: KubernetesLivenessProbe
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            httpHeaders:
              - name: Host
                value: KubernetesReadinessProbe
        env:
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: go-test-config
                key: log_level
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: go-test-secret
                key: user
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: go-test-secret
                key: password
