apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-test-server
  namespace: go-test-server
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: go-test-server
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 30
