apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-server
  namespace: test-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: test-server
    spec:
      containers:
      - name: test-server
        image: grimoh/test-server:1.0.1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
          requests:
            memory: "256Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
              - name: Host
                value: KubernetesLivenessProbe
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            httpHeaders:
              - name: Host
                value: KubernetesReadinessProbe
